name: BuildOnDevelopPush

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore UtilityComplaints.sln

    - name: Build solution
      run: dotnet build UtilityComplaints.sln --configuration Release

    - name: Publish wwwroot
      run: cp -r UtilityComplaints.WebUI/wwwroot UtilityComplaints.WebUI/bin/Release/net7.0

    - name: Run tests
      run: dotnet test UtilityComplaints.sln --configuration Release
      continue-on-error: true

    - name: Publish artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: UtilityComplaints.WebUI/bin/Release/net7.0
